spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    java.sql: debug
    com.teemo.schoolmap: debug
mybatis:
  mapper-locations: classpath*:com/teemo/schoolmap/**/*Mapper.xml
server:
  port: 8081